export enum EnvEnum {
  PORT = 'PORT',
  ENVIRONMENT = 'ENVIRONMENT',
  LOG_LEVEL = 'LOG_LEVEL',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_USER = 'DATABASE_USER',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_NAME = 'DATABASE_NAME',
  DATABASE_SCHEMA = 'DATABASE_SCHEMA',
  DATABASE_HOST = 'DATABASE_HOST',
}
