export enum EnvEnum {
  PORT = 'PORT',
  ENVIRONMENT = 'ENVIRONMENT',
  LOG_LEVEL = 'LOG_LEVEL',

  USERS_DATABASE_HOST = 'USERS_DATABASE_HOST',
  USERS_DATABASE_NAME = 'USERS_DATABASE_NAME',
  USERS_DATABASE_USER = 'USERS_DATABASE_USER',
  USERS_DATABASE_PASSWORD = 'USERS_DATABASE_PASSWORD',
  USERS_DATABASE_SCHEMA = 'USERS_DATABASE_SCHEMA',
  USERS_DATABASE_PORT = 'USERS_DATABASE_PORT',

  TASKS_DATABASE_HOST = 'TASKS_DATABASE_HOST',
  TASKS_DATABASE_NAME = 'TASKS_DATABASE_NAME',
  TASKS_DATABASE_USER = 'TASKS_DATABASE_USER',
  TASKS_DATABASE_PASSWORD = 'TASKS_DATABASE_PASSWORD',
  TASKS_DATABASE_SCHEMA = 'TASKS_DATABASE_SCHEMA',
  TASKS_DATABASE_PORT = 'TASKS_DATABASE_PORT',
}
